=== AlexL5673/robertalab/RobertaIsBlockly/src/main/resources/blockly.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--W3C Schema erstellt mit XMLSpy v2011 rel. 3 sp1 (http://www.altova.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://de.fhg.iais.roberta.blockly" targetNamespace="http://de.fhg.iais.roberta.blockly"
    elementFormDefault="qualified">
    <xs:element name="block">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="mutation" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="field" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="value" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="statement" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="repetitions" minOccurs="0"/>
            </xs:sequence>
            <xs:attribute name="x" type="xs:string" use="optional"/>
            <xs:attribute name="y" type="xs:string" use="optional"/>
            <xs:attribute name="id" type="xs:string" use="required"/>
            <xs:attribute name="type" type="xs:string" use="required"/>
            <xs:attribute name="inline" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="field">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:attribute name="name" type="xs:string" use="required"/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>
    <xs:element name="value">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="block"/>
            </xs:sequence>
            <xs:attribute name="name" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="statement">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="block" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="name" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="repetitions">
        <xs:complexType>
            <xs:sequence minOccurs="0" maxOccurs="unbounded">
                <xs:element ref="value" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="statement" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="mutation">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="arg" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="elseif" type="xs:integer" use="optional"/>
            <xs:attribute name="else" type="xs:integer" use="optional"/>
            <xs:attribute name="value" type="xs:integer" use="optional"/>
            <xs:attribute name="at" type="xs:boolean" use="optional"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="top">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="block" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="x" type="xs:string"/>
            <xs:attribute name="y" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="arg">
        <xs:complexType>
            <xs:attribute name="name" type="xs:string"/>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== AlexL5673/robertalab/RobertaIsBlockly/src/test/resources/blockly-test-1.xml
<?xml version="1.0" encoding="UTF-8"?>
<block type="controls_repeat_ext" id="8" inline="true" x="69" y="109"
       xmlns="http://de.fhg.iais.roberta.blockly"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       schemaLocation="http://de.fhg.iais.roberta.blockly file:///C:/downloads/doc/android/roberta/workspace/blockly.xsd"
>
    <value name="TIMES">
        <block id="21" type="math_number">
            <field name="NUM">5</field>
        </block>
    </value>
    <statement name="DO">
        <block type="controls_repeat_ext" id="9" inline="true">
            <value name="TIMES">
                <block id="22" type="math_number">
                    <field name="NUM">0</field>
                </block>
            </value>
            <statement name="DO">
                <block type="controls_if" id="10" inline="false">
                    <value name="IF0">
                        <block id="23" type="logic_compare" inline="true">
                            <field name="OP">LT</field>
                            <value name="A">
                                <block id="24" type="math_number">
                                    <field name="NUM">0</field>
                                </block>
                            </value>
                            <value name="B">
                                <block id="25" type="math_number">
                                    <field name="NUM">0</field>
                                </block>
                            </value>
                        </block>
                        <statement name="DO0">
                            <block id="16" type="text_print" inline="false">
                                <value name="TEXT">
                                    <block id="17" type="math_arithmetic" inline="true">
                                        <field name="OP">ADD</field>
                                        <value name="A">
                                            <block id="18" type="math_number">
                                                <field name="NUM">0</field>
                                            </block>
                                        </value>
                                        <value name="B">
                                            <block id="19" type="math_number">
                                                <field name="NUM">0</field>
                                            </block>
                                        </value>
                                    </block>
                                </value>
                            </block>
                        </statement>
                    </value>
                </block>
            </statement>
        </block>
    </statement>
</block>
